"""empty message

Revision ID: 42aa1bf2e704
Revises: None
Create Date: 2016-05-29 19:49:19.575213

"""

# revision identifiers, used by Alembic.
revision = '42aa1bf2e704'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bibcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citing_article', sa.Integer(), nullable=True),
    sa.Column('references_article', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['citing_article'], ['article.id'], ),
    sa.ForeignKeyConstraint(['references_article'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    op.drop_table('article')
    ### end Alembic commands ###
